// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package receivepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ReportServerClient is the client API for ReportServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReportServerClient interface {
	// Report
	Report(ctx context.Context, in *ReportReq, opts ...grpc.CallOption) (*ReportRsp, error)
}

type reportServerClient struct {
	cc grpc.ClientConnInterface
}

func NewReportServerClient(cc grpc.ClientConnInterface) ReportServerClient {
	return &reportServerClient{cc}
}

func (c *reportServerClient) Report(ctx context.Context, in *ReportReq, opts ...grpc.CallOption) (*ReportRsp, error) {
	out := new(ReportRsp)
	err := c.cc.Invoke(ctx, "/receive.ReportServer/Report", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReportServerServer is the server API for ReportServer service.
// All implementations must embed UnimplementedReportServerServer
// for forward compatibility
type ReportServerServer interface {
	// Report
	Report(context.Context, *ReportReq) (*ReportRsp, error)
	mustEmbedUnimplementedReportServerServer()
}

// UnimplementedReportServerServer must be embedded to have forward compatible implementations.
type UnimplementedReportServerServer struct {
}

func (UnimplementedReportServerServer) Report(context.Context, *ReportReq) (*ReportRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Report not implemented")
}
func (UnimplementedReportServerServer) mustEmbedUnimplementedReportServerServer() {}

// UnsafeReportServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReportServerServer will
// result in compilation errors.
type UnsafeReportServerServer interface {
	mustEmbedUnimplementedReportServerServer()
}

func RegisterReportServerServer(s grpc.ServiceRegistrar, srv ReportServerServer) {
	s.RegisterService(&ReportServer_ServiceDesc, srv)
}

func _ReportServer_Report_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServerServer).Report(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/receive.ReportServer/Report",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServerServer).Report(ctx, req.(*ReportReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ReportServer_ServiceDesc is the grpc.ServiceDesc for ReportServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReportServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "receive.ReportServer",
	HandlerType: (*ReportServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Report",
			Handler:    _ReportServer_Report_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent2receive.receivepb",
}
