admin:
  listen: ":8083"
  server: ":8082"
store:
  listen: "119.91.150.124:8080"
alert:
  listen: "127.0.0.1:8081"
rule:
  method: 1
  period: "5m"
  threshold:
    warn: 0.03
    error: 0.06
    panic: 0.08