InfluxDB:   # InfluxDB配置
  URL: http://127.0.0.1:9096/ # http://81.71.165.211:8086/
  ORG: debug
  Token: CZ5ZuD-j5XtbTHDmG_RHIuHuu8LU2UOhTSp02hpR6z9hMPk4-5ETiNuYtFrNYDghHq0OLHxSCQA4vBEhm6OJpA== # W494CW95RhZzEc95DpxubUw19EoBuKxCxAlv3YfVCS4KRmYnJf6MhPJGWXFvzkX4hJ76-ZDBIwpV2D76wIZMcA==
  Bucket: metric
  BatchSize: 20   # 批处理数量
  LogLevel: 0
  FlushIntervalMs: 1000     # 单位为ms
  RetryInterval: 5000
  MaxRetryIntervalMs: 125000  # 单位为ms
  MaxRetries: 5
  MaxRetryTime: 180000
  ExponentialBase: 2
  UseGZip: False
  RetryBufferLimit: 50000
  Precision: 1      # 单位为ns
  HttpRequestTimeout: 20  # 单位为s
MySQL:     # MySQL配置
  DBType: mysql
  Username: root
  Password: root # tx-monitor-gdut-group2
  Host: 127.0.0.1:3306 # 81.71.165.211:3307
  DBName: monitor
  Charset: utf8mb4
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 10
  MaxLifetime: 3
Hosts:
  Network: tcp
  Server: 127.0.0.1:8080