InfluxDB:   # InfluxDB配置
  URL: http://81.71.165.211:8086/
  ORG: tx-monitor
  Token: W494CW95RhZzEc95DpxubUw19EoBuKxCxAlv3YfVCS4KRmYnJf6MhPJGWXFvzkX4hJ76-ZDBIwpV2D76wIZMcA==
  Bucket: metric
  BatchSize: 1000   # 批处理数量
  LogLevel: 0
  FlushIntervalMs: 1000     # 单位为ms
  RetryInterval: 5000
  MaxRetryIntervalMs: 125000  # 单位为ms
  MaxRetries: 5
  MaxRetryTime: 180000
  ExponentialBase: 2
  UseGZip: False
  RetryBufferLimit: 50000
  Precision: 1      # 单位为ns
  HttpRequestTimeout: 20  # 单位为s
MySQL:     # MySQL配置
  DBType: mysql
  Username: root
  Password: tx-monitor-gdut-group2
  Host: 81.71.165.211:3307
  DBName: monitor
  Charset: utf8mb4
  ParseTime: True
  MaxIdleConns: 100
  MaxOpenConns: 100
  MaxLifetime: 3
Hosts:
  Network: tcp
  Server: 127.0.0.1:8080
Workers:
  Capacity: 1000       # 协程池容量
  ExpiryDuration: 30s   # 协程过期时间，过期后的协程会被清理
  Nonblocking: false    # 非阻塞提交，默认否，任务无worker执行时阻塞，当为true时，无worker则立即返回nil
  PreAlloc: false       # 内存预分配，是否初始化Pool的时候分配worker资源
  MaxBlockingTasks: 0   # 最大阻塞任务数，默认0，任务阻塞直到分配到worker；当非0时，达到最大任务数，不执行任务并返回overload