// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.3
// source: judgment2store.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetricAlert struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Metric    string  `protobuf:"bytes,1,opt,name=Metric,proto3" json:"Metric,omitempty"`
	Value     float64 `protobuf:"fixed64,2,opt,name=Value,proto3" json:"Value,omitempty"`
	Threshold float64 `protobuf:"fixed64,3,opt,name=Threshold,proto3" json:"Threshold,omitempty"`
	Method    int32   `protobuf:"varint,4,opt,name=Method,proto3" json:"Method,omitempty"`
	Level     int32   `protobuf:"varint,5,opt,name=Level,proto3" json:"Level,omitempty"`
	Duration  string  `protobuf:"bytes,6,opt,name=Duration,proto3" json:"Duration,omitempty"`
	Start     int64   `protobuf:"varint,7,opt,name=Start,proto3" json:"Start,omitempty"`
}

func (x *MetricAlert) Reset() {
	*x = MetricAlert{}
	if protoimpl.UnsafeEnabled {
		mi := &file_judgment2store_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetricAlert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricAlert) ProtoMessage() {}

func (x *MetricAlert) ProtoReflect() protoreflect.Message {
	mi := &file_judgment2store_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricAlert.ProtoReflect.Descriptor instead.
func (*MetricAlert) Descriptor() ([]byte, []int) {
	return file_judgment2store_proto_rawDescGZIP(), []int{0}
}

func (x *MetricAlert) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *MetricAlert) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *MetricAlert) GetThreshold() float64 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *MetricAlert) GetMethod() int32 {
	if x != nil {
		return x.Method
	}
	return 0
}

func (x *MetricAlert) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *MetricAlert) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *MetricAlert) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

type AlertInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgenID  string                  `protobuf:"bytes,1,opt,name=AgenID,proto3" json:"AgenID,omitempty"`
	Metrics map[string]*MetricAlert `protobuf:"bytes,2,rep,name=Metrics,proto3" json:"Metrics,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *AlertInfoRequest) Reset() {
	*x = AlertInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_judgment2store_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlertInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertInfoRequest) ProtoMessage() {}

func (x *AlertInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_judgment2store_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertInfoRequest.ProtoReflect.Descriptor instead.
func (*AlertInfoRequest) Descriptor() ([]byte, []int) {
	return file_judgment2store_proto_rawDescGZIP(), []int{1}
}

func (x *AlertInfoRequest) GetAgenID() string {
	if x != nil {
		return x.AgenID
	}
	return ""
}

func (x *AlertInfoRequest) GetMetrics() map[string]*MetricAlert {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type AlertInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *AlertInfoResponse) Reset() {
	*x = AlertInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_judgment2store_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlertInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertInfoResponse) ProtoMessage() {}

func (x *AlertInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_judgment2store_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertInfoResponse.ProtoReflect.Descriptor instead.
func (*AlertInfoResponse) Descriptor() ([]byte, []int) {
	return file_judgment2store_proto_rawDescGZIP(), []int{2}
}

func (x *AlertInfoResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AlertInfoResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type AggregatedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Method     int32             `protobuf:"varint,1,opt,name=Method,proto3" json:"Method,omitempty"`
	Period     string            `protobuf:"bytes,2,opt,name=Period,proto3" json:"Period,omitempty"`
	Metric     string            `protobuf:"bytes,3,opt,name=Metric,proto3" json:"Metric,omitempty"`
	Value      float64           `protobuf:"fixed64,4,opt,name=Value,proto3" json:"Value,omitempty"`
	IP         string            `protobuf:"bytes,5,opt,name=IP,proto3" json:"IP,omitempty"`
	Local      string            `protobuf:"bytes,6,opt,name=Local,proto3" json:"Local,omitempty"`
	Port       string            `protobuf:"bytes,7,opt,name=Port,proto3" json:"Port,omitempty"`
	Timestamp  int64             `protobuf:"varint,8,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Dimensions map[string]string `protobuf:"bytes,9,rep,name=Dimensions,proto3" json:"Dimensions,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *AggregatedRequest) Reset() {
	*x = AggregatedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_judgment2store_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AggregatedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregatedRequest) ProtoMessage() {}

func (x *AggregatedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_judgment2store_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregatedRequest.ProtoReflect.Descriptor instead.
func (*AggregatedRequest) Descriptor() ([]byte, []int) {
	return file_judgment2store_proto_rawDescGZIP(), []int{3}
}

func (x *AggregatedRequest) GetMethod() int32 {
	if x != nil {
		return x.Method
	}
	return 0
}

func (x *AggregatedRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *AggregatedRequest) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *AggregatedRequest) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *AggregatedRequest) GetIP() string {
	if x != nil {
		return x.IP
	}
	return ""
}

func (x *AggregatedRequest) GetLocal() string {
	if x != nil {
		return x.Local
	}
	return ""
}

func (x *AggregatedRequest) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *AggregatedRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AggregatedRequest) GetDimensions() map[string]string {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

type AggregatedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code  int32   `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg   string  `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	Value float64 `protobuf:"fixed64,3,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *AggregatedResponse) Reset() {
	*x = AggregatedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_judgment2store_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AggregatedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregatedResponse) ProtoMessage() {}

func (x *AggregatedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_judgment2store_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregatedResponse.ProtoReflect.Descriptor instead.
func (*AggregatedResponse) Descriptor() ([]byte, []int) {
	return file_judgment2store_proto_rawDescGZIP(), []int{4}
}

func (x *AggregatedResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AggregatedResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *AggregatedResponse) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_judgment2store_proto protoreflect.FileDescriptor

var file_judgment2store_proto_rawDesc = []byte{
	0x0a, 0x14, 0x6a, 0x75, 0x64, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x32, 0x73, 0x74, 0x6f, 0x72, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb9, 0x01,
	0x0a, 0x0b, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4d,
	0x65, 0x74, 0x72, 0x69, 0x63, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x54,
	0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09,
	0x54, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x4d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x4d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x44, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x72, 0x74, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x53, 0x74, 0x61, 0x72, 0x74, 0x22, 0xba, 0x01, 0x0a, 0x10, 0x41, 0x6c,
	0x65, 0x72, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x41, 0x67, 0x65, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x41, 0x67, 0x65, 0x6e, 0x49, 0x44, 0x12, 0x3e, 0x0a, 0x07, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x41, 0x6c, 0x65, 0x72, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x4d,
	0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x1a, 0x4e, 0x0a, 0x0c, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x28, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x39, 0x0a, 0x11, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73,
	0x67, 0x22, 0xd2, 0x02, 0x0a, 0x11, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x4d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x4d, 0x65, 0x74, 0x72, 0x69,
	0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x12,
	0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x50, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x49, 0x50, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x50,
	0x6f, 0x72, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x50, 0x6f, 0x72, 0x74, 0x12,
	0x1c, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x48, 0x0a,
	0x0a, 0x44, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x28, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67,
	0x61, 0x74, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x44, 0x69, 0x6d, 0x65,
	0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0a, 0x44, 0x69, 0x6d,
	0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x3d, 0x0a, 0x0f, 0x44, 0x69, 0x6d, 0x65, 0x6e,
	0x73, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x50, 0x0a, 0x12, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67,
	0x61, 0x74, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d,
	0x73, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x32, 0xa3, 0x01, 0x0a, 0x0d, 0x4d, 0x65, 0x74,
	0x72, 0x69, 0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4a, 0x0a, 0x11, 0x47, 0x65,
	0x74, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74,
	0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0f, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74,
	0x41, 0x6c, 0x65, 0x72, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x6c, 0x65, 0x72, 0x74,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x09,
	0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_judgment2store_proto_rawDescOnce sync.Once
	file_judgment2store_proto_rawDescData = file_judgment2store_proto_rawDesc
)

func file_judgment2store_proto_rawDescGZIP() []byte {
	file_judgment2store_proto_rawDescOnce.Do(func() {
		file_judgment2store_proto_rawDescData = protoimpl.X.CompressGZIP(file_judgment2store_proto_rawDescData)
	})
	return file_judgment2store_proto_rawDescData
}

var file_judgment2store_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_judgment2store_proto_goTypes = []interface{}{
	(*MetricAlert)(nil),        // 0: proto.MetricAlert
	(*AlertInfoRequest)(nil),   // 1: proto.AlertInfoRequest
	(*AlertInfoResponse)(nil),  // 2: proto.AlertInfoResponse
	(*AggregatedRequest)(nil),  // 3: proto.AggregatedRequest
	(*AggregatedResponse)(nil), // 4: proto.AggregatedResponse
	nil,                        // 5: proto.AlertInfoRequest.MetricsEntry
	nil,                        // 6: proto.AggregatedRequest.DimensionsEntry
}
var file_judgment2store_proto_depIdxs = []int32{
	5, // 0: proto.AlertInfoRequest.Metrics:type_name -> proto.AlertInfoRequest.MetricsEntry
	6, // 1: proto.AggregatedRequest.Dimensions:type_name -> proto.AggregatedRequest.DimensionsEntry
	0, // 2: proto.AlertInfoRequest.MetricsEntry.value:type_name -> proto.MetricAlert
	3, // 3: proto.MetricService.GetAggregatedData:input_type -> proto.AggregatedRequest
	1, // 4: proto.MetricService.InsertAlertInfo:input_type -> proto.AlertInfoRequest
	4, // 5: proto.MetricService.GetAggregatedData:output_type -> proto.AggregatedResponse
	2, // 6: proto.MetricService.InsertAlertInfo:output_type -> proto.AlertInfoResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_judgment2store_proto_init() }
func file_judgment2store_proto_init() {
	if File_judgment2store_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_judgment2store_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetricAlert); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_judgment2store_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlertInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_judgment2store_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlertInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_judgment2store_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AggregatedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_judgment2store_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AggregatedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_judgment2store_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_judgment2store_proto_goTypes,
		DependencyIndexes: file_judgment2store_proto_depIdxs,
		MessageInfos:      file_judgment2store_proto_msgTypes,
	}.Build()
	File_judgment2store_proto = out.File
	file_judgment2store_proto_rawDesc = nil
	file_judgment2store_proto_goTypes = nil
	file_judgment2store_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MetricServiceClient is the client API for MetricService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MetricServiceClient interface {
	// 获取聚合数据
	GetAggregatedData(ctx context.Context, in *AggregatedRequest, opts ...grpc.CallOption) (*AggregatedResponse, error)
	// 插入告警信息
	InsertAlertInfo(ctx context.Context, in *AlertInfoRequest, opts ...grpc.CallOption) (*AlertInfoResponse, error)
}

type metricServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMetricServiceClient(cc grpc.ClientConnInterface) MetricServiceClient {
	return &metricServiceClient{cc}
}

func (c *metricServiceClient) GetAggregatedData(ctx context.Context, in *AggregatedRequest, opts ...grpc.CallOption) (*AggregatedResponse, error) {
	out := new(AggregatedResponse)
	err := c.cc.Invoke(ctx, "/proto.MetricService/GetAggregatedData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricServiceClient) InsertAlertInfo(ctx context.Context, in *AlertInfoRequest, opts ...grpc.CallOption) (*AlertInfoResponse, error) {
	out := new(AlertInfoResponse)
	err := c.cc.Invoke(ctx, "/proto.MetricService/InsertAlertInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetricServiceServer is the server API for MetricService service.
type MetricServiceServer interface {
	// 获取聚合数据
	GetAggregatedData(context.Context, *AggregatedRequest) (*AggregatedResponse, error)
	// 插入告警信息
	InsertAlertInfo(context.Context, *AlertInfoRequest) (*AlertInfoResponse, error)
}

// UnimplementedMetricServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMetricServiceServer struct {
}

func (*UnimplementedMetricServiceServer) GetAggregatedData(context.Context, *AggregatedRequest) (*AggregatedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAggregatedData not implemented")
}
func (*UnimplementedMetricServiceServer) InsertAlertInfo(context.Context, *AlertInfoRequest) (*AlertInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertAlertInfo not implemented")
}

func RegisterMetricServiceServer(s *grpc.Server, srv MetricServiceServer) {
	s.RegisterService(&_MetricService_serviceDesc, srv)
}

func _MetricService_GetAggregatedData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AggregatedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricServiceServer).GetAggregatedData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MetricService/GetAggregatedData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricServiceServer).GetAggregatedData(ctx, req.(*AggregatedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetricService_InsertAlertInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlertInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricServiceServer).InsertAlertInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MetricService/InsertAlertInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricServiceServer).InsertAlertInfo(ctx, req.(*AlertInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MetricService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.MetricService",
	HandlerType: (*MetricServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAggregatedData",
			Handler:    _MetricService_GetAggregatedData_Handler,
		},
		{
			MethodName: "InsertAlertInfo",
			Handler:    _MetricService_InsertAlertInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "judgment2store.proto",
}
